image: node:latest

cache:
  paths:
    - node_modules/

build:
  stage: build

pages:
  stage: deploy
  environment: production
  script:
    - npm install
    - npm run build-prod
    - echo "The site will be deployed to $CI_PAGES_URL and https://playmusichtml.web.app"
    
  artifacts:
    paths:
      - ./public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
