image: node:latest

before_script:
  - npm install -g firebase-tools uglify-js clean-css-cli

minify_js:
  stage: build
  script:
    - 'for file in ./public/js/*.js; do uglifyjs "$file" -o "${file%.js}.min.js"; done'

minify_css:
  stage: build
  script:
    - 'for file in ./public/css/*.css; do cleancss "$file" -o "${file%.css}.min.css"; done'

pages:
  stage: deploy
  environment: production
  script:
    - echo "Deploying to Firebase"
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
    - echo "The site will be deployed to $CI_PAGES_URL and https://playmusichtml.web.app"
    
  artifacts:
    paths:
      - ./public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH