image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - npm install -g firebase-tools 

build:
  stage: build
  script:
    - npm run build-prod

pages:
  stage: deploy
  environment: production
  script:
    - echo "Deploying to Firebase"
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
    - echo "The site will be deployed to $CI_PAGES_URL and https://playmusichtml.web.app"
    
  artifacts:
    paths:
      - ./public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
