# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# Full project: https://gitlab.com/pages/plain-html
image: node:21.7.2-alpine

deploy-on-firebase:
  stage: pre
  script:
    - npm i -g firebase-tools
    - npm install
  stage: deploy-firebase
  script:
    - firebase deploy --only hosting --token FIREBASE_TOKEN

pages:
  stage: deploy-pages
  environment: production
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - ./public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
