name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Set up Firebase service account
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > "${HOME}/firebase-service-account.json"
      shell: bash

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLAYMUSICHTML }}
          projectId: playmusichtml
